name: accent-soft
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - aom=3.9.1
  - audioread=3.0.1
  - backports.zstd=1.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cython=3.2.4
  - dav1d=1.2.1
  - dbus=1.16.2
  - decorator=5.2.1
  - ffmpeg=8.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glslang=16.1.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=78.2
  - importlib-metadata=8.7.0
  - kiwisolver=1.4.9
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libhwloc=2.12.2
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.4.1
  - libopenvino-arm-cpu-plugin=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - librosa=0.11.0
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - llvmlite=0.46.0
  - matplotlib-base=3.10.8
  - mpg123=1.32.9
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - ncurses=6.5
  - numba=0.63.1
  - numpy=1.26.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.1
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pooch=1.8.2
  - pthread-stubs=0.4
  - pugixml=1.15
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyworld=0.3.5
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - sdl2=2.32.56
  - sdl3=3.2.30
  - setuptools=80.9.0
  - shaderc=2025.5
  - six=1.17.0
  - snappy=1.2.2
  - soxr=0.1.3
  - soxr-python=1.0.0
  - spirv-tools=2025.4
  - standard-aifc=3.13.0
  - standard-sunau=3.13.0
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - tk=8.6.13
  - typing_extensions=4.15.0
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.3
      - anyio==4.12.1
      - appdirs==1.4.4
      - asteroid-filterbanks==0.4.0
      - attrs==25.4.0
      - av==15.1.0
      - babel==2.17.0
      - backports-functools-lru-cache==2.0.0
      - bangla==0.0.5
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - blis==1.3.3
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - catalogue==2.0.10
      - cefrpy==1.0.1
      - certifi==2025.11.12
      - chardet==3.0.4
      - click==8.1.3
      - cloudpathlib==0.23.0
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - confection==0.1.5
      - coqpit==0.0.17
      - csvw==3.7.0
      - ctranslate2==4.6.2
      - cymem==2.0.13
      - dateparser==1.1.8
      - deep-translator==1.11.4
      - deepfilterlib==0.5.6
      - deepfilternet==0.5.6
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - dlinfo==2.0.0
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - fastapi==0.128.0
      - fastdtw==0.3.4
      - faster-whisper==1.2.1
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - g2pkk==0.1.2
      - gensim==4.4.0
      - gradio==4.15.0
      - gradio-client==0.8.1
      - groovy==0.1.2
      - grpcio==1.76.0
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - gtts==2.5.4
      - h11==0.16.0
      - h2==3.2.0
      - hangul-romanize==0.1.0
      - hf-xet==1.2.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==1.0.9
      - httpx==0.25.2
      - huggingface-hub==0.19.4
      - humanfriendly==10.0
      - hyperframe==5.2.0
      - hyperpyyaml==1.2.2
      - idna==3.6
      - importlib-resources==6.5.2
      - indic-transliteration==2.3.76
      - inflect==7.5.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jaconv==0.4.1
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.2.0
      - jsonlines==1.2.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - julius==0.2.7
      - langdetect==1.0.9
      - language-tags==1.2.0
      - levenshtein==0.27.3
      - lightning==2.4.0
      - lightning-utilities==0.15.2
      - loguru==0.7.3
      - lru-dict==1.4.1
      - lupa==2.6
      - mako==1.3.10
      - markdown==3.10.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mlconjug3==3.11.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - murmurhash==1.0.15
      - mwparserfromhell==0.7.2
      - narwhals==2.15.0
      - networkx==2.8.8
      - nltk==3.9.2
      - num2words==0.5.14
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - optuna==4.6.0
      - orjson==3.11.5
      - packaging==23.2
      - pandas==1.5.3
      - phonemizer==3.3.0
      - pillow==10.4.0
      - preshed==3.0.12
      - primepy==1.3
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - py-espeak-ng==0.1.8
      - pyannote-audio==3.4.0
      - pyannote-core==5.0.0
      - pyannote-database==5.1.3
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pykakasi==2.3.0
      - pynndescent==0.6.0
      - pyparsing==3.2.5
      - pypinyin==0.55.0
      - pysbd==0.3.4
      - python-crfsuite==0.9.12
      - python-dotenv==1.2.1
      - python-levenshtein==0.27.3
      - python-multipart==0.0.22
      - python-telegram-bot==20.7
      - python-utils==3.4.5
      - pytorch-lightning==2.4.0
      - pytorch-metric-learning==2.9.0
      - pytz==2025.2
      - pyyaml==6.0
      - rapidfuzz==3.14.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rfc3986==1.5.0
      - rich==13.2.0
      - roman==5.2
      - rpds-py==0.30.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - ruff==0.14.14
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-learn==1.3.0
      - scipy==1.16.3
      - segments==2.3.0
      - semantic-version==2.10.0
      - semver==3.0.4
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - smart-open==7.5.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8.3
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechbrain==1.0.3
      - sqlalchemy==2.0.45
      - srsly==2.5.2
      - starlette==0.50.0
      - sudachidict-core==20260116
      - sudachipy==0.6.10
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.3.0
      - thinc==8.3.10
      - threadpoolctl==3.1.0
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomlkit==0.11.6
      - torch==2.5.1
      - torch-audiomentations==0.12.0
      - torch-pitch-shift==1.2.5
      - torchaudio==2.5.1
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - trainer==0.0.36
      - transformers==4.38.2
      - tts==0.22.0
      - typeguard==4.4.4
      - typer==0.20.1
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - umap-learn==0.5.11
      - unidecode==1.4.0
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - websockets==11.0.3
      - werkzeug==3.1.5
      - whisperx==3.6.0
      - wikitextprocessor==0.4.96
      - wiktextract==1.99.7
      - wiktionaryparser==0.0.97
      - wrapt==2.0.1
      - yarl==1.22.0
prefix: /Users/Alex/miniforge3/envs/accent-soft
