name: accent-soft
channels:
  - conda-forge
dependencies:
  - python=3.11
  - librosa
  - numpy>=1.26,<2.0
  - pyworld
  - pip
  - pip:
      - pytest-asyncio
      - anyio[trio]
      - pytest
      - ctranslate2==4.6.2
      - gradio==4.15.0
      - gradio-client==0.8.1
      - torch>=2.7.1
      - torchaudio
      - transformers==4.38.2
      - pyannote-audio==3.4.0
      - speechbrain==1.0.3
      - TTS==0.22.0
      - deepfilternet==0.5.6
      - python-dotenv==1.2.1
      - fastapi==0.128.0
      - uvicorn==0.40.0
      - deep-translator
      - gtts
      - fastdtw
      - inflect
      - mwparserfromhell
      - sentence-transformers
      - soundfile
      - python-telegram-bot==20.7
      - scipy
      - matplotlib
      - requests
      - setuptools